### ISSUE TITLE
Add tw comment to allow tagging string as tailwind strings

### ISSUE THREAD

**Issue by james2doyle** [paolotiu/tailwind-intellisense-regex-list#19]
I am using the following regex to allow me to "tag" a string with a comment so that it acts as a tailwind string and enables autocomplete to work on it.

```
"@tw\\s\\*\/\\s+[\"'`]([^\"'`]*)"
```

![image](https://github.com/paolotiu/tailwind-intellisense-regex-list/assets/1425304/15706edb-8bcf-4ef1-b0ca-355f99803673)

**Comment by paolotiu** [comment]
Sorry for getting back to this very late! Thanks for this :D
