### ISSUE TITLE
twMerge regex doesn`t work if class name includes some arbitrary values

### ISSUE THREAD

**Issue by musme** [paolotiu/tailwind-intellisense-regex-list#22]
Hi, 
[tailwind-merge Regex ](https://github.com/paolotiu/tailwind-intellisense-regex-list#tailwind-merge) doesn`t work for classes with expression **)]**
i.e.
```
twJoin("w-[calc(1.25rem-6px)]");
twJoin("[&:not(:disabled)]:cursor-pointer");
```
Created regex101 link:
https://regex101.com/r/MYwru6/1

**Comment by paolotiu** [comment]
Hi @musme! Thanks for bringing this up. Can you try  if this works for you?

```json
 [
      "(?:twMerge|twJoin)\\(([\"'`\\[\\{]?[^\\;]*?[\"'`\\]\\}])(?:\\n*[\\);\\}]|,\\)|\n*,\n*\\))",
      "[`'\"`]([^'\"`,;]*)[`'\"`]"
 ]
```
https://regex101.com/r/h3TFgC/1

**Comment by musme** [comment]
Hi, @paolotiu!
Doesn`t work as expected in many cases.

For example if I write classes using line breaks the regex doesnt`t work

```
twJoin(
  "text-ellipsis",
  "text-clip"
)
```

But it works if I put some comment like //") in the next line.


https://github.com/paolotiu/tailwind-intellisense-regex-list/assets/11893082/c3e5db43-09a3-4aac-b05a-9f5f798ae74f

**Comment by paolotiu** [comment]
Thanks for this! I didn't account for these cases. I'll make a few edits then post it here again

**Comment by musme** [comment]
@paolotiu, thank you!

**Comment by paolotiu** [comment]
Hello @musme! Sorry for getting back to you really really late! 

Can you try if this works for you?

```json
  "tailwindCSS.experimental.classRegex": [
    ["(?:twMerge|twJoin)\\(([^;]*)[\\);]", "[`'\"`]([^'\"`,;]*)[`'\"`]"]
  ]
```

**Comment by musme** [comment]
> Hello @musme! Sorry for getting back to you really really late!
> 
> Can you try if this works for you?
> 
> ```json
>   "tailwindCSS.experimental.classRegex": [
>     ["(?:twMerge|twJoin)\\(([^;]*)[\\);]", "[`'\"`]([^'\"`,;]*)[`'\"`]"]
>   ]
> ```

@paolotiu, hello! Thank you!!! It works in most cases. By now I found only one case then it doesnt`t work as expected.

Take a look at this code:

``` js 
const switchClassName = twJoin(
    "pointer-events-none absolute top-[2px] rounded-full transition-[background-color,left] bg-white",
    "left-[2px] h-4 w-4",
    "peer-checked:left-[17px]",
    "peer-[:not(:checked):disabled]:opacity-50"
  );
```
There is "transition-[background-color,left]" class in the first line. Arbitrary value includes comma. The comma brakes the class hinting. But everything is ok on the next lines.

I think this regex fully covers my needs. Thanks again!

By the way I recorded this behavior.

https://github.com/paolotiu/tailwind-intellisense-regex-list/assets/11893082/ef51698c-c549-4445-98f9-d5ef30267ede

**Comment by paolotiu** [comment]
This updated one should fix the behavior!

```json
  "tailwindCSS.experimental.classRegex": [
    ["(?:twMerge|twJoin)\\(([^;]*)[\\);]", "[`'\"`]([^'\"`;]*)[`'\"`]"]
  ]
```

Thanks for giving the video and code! It was a big help

**Comment by musme** [comment]
@paolotiu, now everything is cool! Thanks a lot!
