### ISSUE TITLE
Regex pattern for props that include ClassName

### ISSUE THREAD

**Issue by brandanking-decently** [paolotiu/tailwind-intellisense-regex-list#25]
Hi, I was wondering on a regex patter that works for props, variables etc that include className. An example of this would be how react-skeleton-loader users a containerClassName prop.

**Comment by paolotiu** [comment]
Can you check if this works for you?

```json
  "tailwindCSS.experimental.classRegex": [
    "[a-zA-Z]*(?:c|C)lass(?:n|N)ame(?:)?=\\s*(?:\"|'|{`)([^(?:\"|'|`})]*)",
  ]
```

**Comment by brandanking-decently** [comment]
Hey, this doesn't seem to work for me

**Comment by paolotiu** [comment]
How about this

```json
  "tailwindCSS.experimental.classRegex": [
    "[a-zA-Z]*(?:c|C)lass(?:n|N)ame(?:)?={?(?:\"|'|`)([^(?:\"|'|`})]*)}?"
  ]
```

**Comment by brandanking-decently** [comment]
This seems to be working now, thank you very much for this

**Comment by martinezguillaume** [comment]
Can we add this regex in the repo ? It is very useful ❤️

**Comment by paolotiu** [comment]
> Can we add this regex in the repo ? It is very useful ❤️

I'll work on adding it!
